import type { TFunction } from 'i18next'
import type { ReactNode } from 'react'

import { GoalCard, StepHeader, StepWrap, Unit, type GoalTone } from './StepParts'

import { DateField } from '@/components/ui/DateField'
import { Select } from '@/components/ui/Select'
import type { Goal, Sex } from '@/types/profile'

/**
 * Step 1: who the person is, and what they are here for.
 *
 * Lifted out of OnboardingPage verbatim, markup untouched. It takes the fields as props
 * rather than owning them because leaving step 2 sends all of this to the server at once,
 * so the flow has to hold the state; owning it here would mean lifting it straight back up.
 */
export function StepAboutYou({
  t,
  ids,
  name,
  setName,
  birthDate,
  setBirthDate,
  sex,
  setSex,
  heightCm,
  setHeightCm,
  weightKg,
  setWeightKg,
  goal,
  setGoal,
  sexOptions,
  goalOptions,
}: {
  t: TFunction
  /** Generated by the page with useId, so each label points at the right control. */
  ids: { name: string; weight: string; height: string; birth: string; sex: string; focus: string }
  name: string
  setName: (value: string) => void
  birthDate: string
  setBirthDate: (value: string) => void
  sex: Sex | ''
  setSex: (value: Sex) => void
  heightCm: string
  setHeightCm: (value: string) => void
  weightKg: string
  setWeightKg: (value: string) => void
  goal: Goal | ''
  setGoal: (value: Goal) => void
  sexOptions: { value: Sex; label: string }[]
  goalOptions: { value: Goal; label: string; hint: string; icon: ReactNode; tone: GoalTone }[]
}) {
  return (
    <StepWrap>
      <StepHeader title={t('onboarding.step1Title')} subtitle={t('onboarding.step1Subtitle')} />

      <div className="mb-4">
        <label htmlFor={ids.name} className="label">
          {t('onboarding.nameLabel')}
        </label>
        <input
          id={ids.name}
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
          placeholder={t('onboarding.namePlaceholder')}
          className="input"
        />
      </div>

      <div className="mb-4 grid grid-cols-2 gap-3">
        <div>
          <label htmlFor={ids.weight} className="label">
            {t('onboarding.weightLabel')}
          </label>
          <Unit unit="kg">
            <input
              id={ids.weight}
              type="number"
              min={20}
              max={500}
              step="0.1"
              value={weightKg}
              onChange={(e) => setWeightKg(e.target.value)}
              placeholder="78"
              className="input pr-10"
            />
          </Unit>
        </div>
        <div>
          <label htmlFor={ids.height} className="label">
            {t('onboarding.heightLabel')}
          </label>
          <Unit unit="cm">
            <input
              id={ids.height}
              type="number"
              min={50}
              max={300}
              step="1"
              value={heightCm}
              onChange={(e) => setHeightCm(e.target.value)}
              placeholder="179"
              className="input pr-10"
            />
          </Unit>
        </div>
      </div>

      <div className="mb-4">
        {/*
                A span rather than a label: a label names a form control, and the three
                dropdowns below are a group, not one. The group reads this text through
                aria-labelledby, which is what actually names it.
              */}
        <span id={ids.birth} className="label block">
          {t('onboarding.birthLabel')}
        </span>
        <DateField labelId={ids.birth} value={birthDate} onChange={setBirthDate} />
      </div>

      <div className="mb-5">
        <label htmlFor={ids.sex} className="label">
          {t('onboarding.sexLabel')}
        </label>
        <Select
          id={ids.sex}
          value={sex}
          onChange={setSex}
          options={sexOptions}
          placeholder={t('onboarding.sexPlaceholder')}
        />
      </div>

      <div>
        {/* A set of cards, not a single control: htmlFor has nothing to point at,
                  so the group carries the name instead. */}
        <p id={ids.focus} className="label">
          {t('onboarding.focusLabel')}
        </p>
        <div role="group" aria-labelledby={ids.focus} className="grid gap-2.5 sm:grid-cols-2">
          {goalOptions.map((g) => (
            <GoalCard
              key={g.value}
              active={goal === g.value}
              label={g.label}
              hint={g.hint}
              icon={g.icon}
              tone={g.tone}
              onClick={() => setGoal(g.value)}
            />
          ))}
        </div>
      </div>
    </StepWrap>
  )
}
