package com.aps.vitalpair.ai.infrastructure.web;

import jakarta.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.aps.vitalpair.ai.application.dto.SwapMealCommand;
import com.aps.vitalpair.ai.domain.port.in.GenerateMealPlanUseCase;
import com.aps.vitalpair.ai.domain.port.in.GetMealPlanUseCase;
import com.aps.vitalpair.ai.domain.port.in.SwapMealUseCase;
import com.aps.vitalpair.shared.security.AuthenticatedUser;
import com.aps.vitalpair.shared.web.ApiResponse;
import com.aps.vitalpair.shared.web.StandardApiResponses;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;

/**
 * The AI weekly meal plan. GET answers {@code data: null} (200) while the user has not generated
 * this week's plan; generating replaces the whole plan.
 */
@Tag(name = "Meal plan", description = "A week of meals generated by AI against the person's calorie target.")
@RestController
@RequestMapping("/api/v1/meal-plan")
public class MealPlanController {

    private final GetMealPlanUseCase getMealPlanUseCase;
    private final GenerateMealPlanUseCase generateMealPlanUseCase;
    private final SwapMealUseCase swapMealUseCase;

    public MealPlanController(
            GetMealPlanUseCase getMealPlanUseCase,
            GenerateMealPlanUseCase generateMealPlanUseCase,
            SwapMealUseCase swapMealUseCase) {
        this.getMealPlanUseCase = getMealPlanUseCase;
        this.generateMealPlanUseCase = generateMealPlanUseCase;
        this.swapMealUseCase = swapMealUseCase;
    }

    @StandardApiResponses
    @Operation(
            summary = "This week's meal plan",
            description =
                    "The plan for the current week, Monday to Sunday, or `data: null` with 200 when none has been generated yet.")
    @GetMapping
    public ResponseEntity<ApiResponse<MealPlanResponse>> current(@AuthenticationPrincipal AuthenticatedUser principal) {
        MealPlanResponse plan = getMealPlanUseCase
                .getCurrentWeekPlan(principal.userId(), principal.tenantId())
                .map(MealPlanResponse::from)
                .orElse(null);
        return ResponseEntity.ok(ApiResponse.ok(plan));
    }

    @StandardApiResponses
    @Operation(
            summary = "Generate the week's meal plan",
            description =
                    "Asks the model for seven days of four meals built on the caller's calorie and macro targets, replacing any existing plan for the week. Refused with 422 before any paid call when the profile has no calorie target. Limited to five generations an hour per user.")
    @PostMapping("/generate")
    public ResponseEntity<ApiResponse<MealPlanResponse>> generate(
            @AuthenticationPrincipal AuthenticatedUser principal) {
        MealPlanResponse plan =
                MealPlanResponse.from(generateMealPlanUseCase.generate(principal.userId(), principal.tenantId()));
        return ResponseEntity.ok(ApiResponse.ok(plan, "Cardápio da semana gerado"));
    }

    @StandardApiResponses
    @Operation(
            summary = "Swap one meal",
            description =
                    "Replaces a single meal (day and meal type) with an alternative of similar calories and macros, leaving the rest of the week untouched. Limited to twenty swaps an hour per user.")
    @PostMapping("/swap")
    public ResponseEntity<ApiResponse<MealPlanResponse>> swap(
            @AuthenticationPrincipal AuthenticatedUser principal, @Valid @RequestBody SwapMealRequest request) {
        MealPlanResponse plan = MealPlanResponse.from(swapMealUseCase.swap(
                principal.userId(), principal.tenantId(), new SwapMealCommand(request.dayIndex(), request.mealType())));
        return ResponseEntity.ok(ApiResponse.ok(plan, "Refeição trocada"));
    }
}
