package com.aps.vitalpair.ai.infrastructure.web;

import java.util.UUID;

import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.aps.vitalpair.ai.domain.port.in.CompleteWorkoutUseCase;
import com.aps.vitalpair.ai.domain.port.in.GenerateWorkoutPlanUseCase;
import com.aps.vitalpair.ai.domain.port.in.GetTodayWorkoutUseCase;
import com.aps.vitalpair.ai.domain.port.in.ToggleWorkoutExerciseUseCase;
import com.aps.vitalpair.shared.security.AuthenticatedUser;
import com.aps.vitalpair.shared.web.ApiResponse;
import com.aps.vitalpair.shared.web.StandardApiResponses;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;

/**
 * The AI weekly workout plan. GET /today answers {@code data: null} (200) while the user has not
 * generated this week's plan. Completing the day logs a WORKOUT activity through the activity
 * feature (points, feed and streak follow automatically); completing twice answers 409.
 */
@Tag(name = "Workout plan", description = "A week of workouts generated by AI, and completing the day's session.")
@RestController
@RequestMapping("/api/v1/workout-plan")
public class WorkoutPlanController {

    private final GetTodayWorkoutUseCase getTodayWorkoutUseCase;
    private final GenerateWorkoutPlanUseCase generateWorkoutPlanUseCase;
    private final ToggleWorkoutExerciseUseCase toggleWorkoutExerciseUseCase;
    private final CompleteWorkoutUseCase completeWorkoutUseCase;

    public WorkoutPlanController(
            GetTodayWorkoutUseCase getTodayWorkoutUseCase,
            GenerateWorkoutPlanUseCase generateWorkoutPlanUseCase,
            ToggleWorkoutExerciseUseCase toggleWorkoutExerciseUseCase,
            CompleteWorkoutUseCase completeWorkoutUseCase) {
        this.getTodayWorkoutUseCase = getTodayWorkoutUseCase;
        this.generateWorkoutPlanUseCase = generateWorkoutPlanUseCase;
        this.toggleWorkoutExerciseUseCase = toggleWorkoutExerciseUseCase;
        this.completeWorkoutUseCase = completeWorkoutUseCase;
    }

    @StandardApiResponses
    @Operation(
            summary = "Today's workout",
            description =
                    "Today's session from this week's plan, with its exercises and whether each is done, or `data: null` with 200 when no plan exists.")
    @GetMapping("/today")
    public ResponseEntity<ApiResponse<WorkoutTodayResponse>> today(
            @AuthenticationPrincipal AuthenticatedUser principal) {
        WorkoutTodayResponse today = getTodayWorkoutUseCase
                .getToday(principal.userId(), principal.tenantId())
                .map(WorkoutTodayResponse::from)
                .orElse(null);
        return ResponseEntity.ok(ApiResponse.ok(today));
    }

    @StandardApiResponses
    @Operation(
            summary = "Generate the week's workout plan",
            description =
                    "Asks the model for seven days with four or five training sessions and rest days, based on the caller's goal and activity level. Refused with 422 when the profile has no goal. Limited to five generations an hour per user.")
    @PostMapping("/generate")
    public ResponseEntity<ApiResponse<WorkoutTodayResponse>> generate(
            @AuthenticationPrincipal AuthenticatedUser principal) {
        WorkoutTodayResponse today = WorkoutTodayResponse.from(
                generateWorkoutPlanUseCase.generate(principal.userId(), principal.tenantId()));
        return ResponseEntity.ok(ApiResponse.ok(today, "Plano de treino da semana gerado"));
    }

    @StandardApiResponses
    @Operation(
            summary = "Tick or untick an exercise",
            description =
                    "Flips the done flag on one exercise of the caller's own plan. An exercise that belongs to another user's plan answers 404.")
    @PostMapping("/exercises/{id}/toggle")
    public ResponseEntity<ApiResponse<WorkoutTodayResponse>> toggle(
            @AuthenticationPrincipal AuthenticatedUser principal, @PathVariable("id") UUID exerciseId) {
        WorkoutTodayResponse today = WorkoutTodayResponse.from(
                toggleWorkoutExerciseUseCase.toggle(principal.userId(), principal.tenantId(), exerciseId));
        return ResponseEntity.ok(ApiResponse.ok(today));
    }

    @StandardApiResponses
    @Operation(
            summary = "Complete today's workout",
            description =
                    "Marks today's session done and logs a WORKOUT activity, which scores points. A rest day answers 422; a day already completed answers 409.")
    @PostMapping("/complete")
    public ResponseEntity<ApiResponse<WorkoutTodayResponse>> complete(
            @AuthenticationPrincipal AuthenticatedUser principal) {
        WorkoutTodayResponse today =
                WorkoutTodayResponse.from(completeWorkoutUseCase.complete(principal.userId(), principal.tenantId()));
        return ResponseEntity.ok(ApiResponse.ok(today, "Treino de hoje concluído"));
    }
}
