/**
 * Feature <b>ai</b>: weekly meal and workout plans generated by a model (Anthropic Claude) from
 * the user's own targets. Plans are regenerated on request; there is no automatic recalibration.
 *
 * <p>Hexagonal layout (see {@code docs/adr/0001-arquitetura-hexagonal.md}): besides
 * {@code domain} and {@code application}, its {@code infrastructure} centres on the
 * {@code client} that calls the model. Dependency rule: infrastructure -> application -> domain.
 */
package com.aps.vitalpair.ai;
