package com.aps.vitalpair.user.infrastructure.storage;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.UUID;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

/**
 * What reaches the filesystem, and what cannot.
 *
 * <p>The traversal cases matter most. The object name is generated by this class, so in normal
 * operation none of them can happen; they are here because the name makes a round trip through
 * the database and comes back as input, and because the next person to touch the pattern needs a
 * test that fails if they loosen it.
 */
class FilesystemAvatarStorageAdapterTest {

    private static final UUID USER = UUID.randomUUID();
    private static final byte[] IMAGE = "pretend this is a jpeg".getBytes(StandardCharsets.UTF_8);

    @TempDir
    Path directory;

    private FilesystemAvatarStorageAdapter adapter;

    @BeforeEach
    void setUp() {
        adapter = new FilesystemAvatarStorageAdapter(directory.toString());
        adapter.prepareDirectory();
    }

    @Test
    void storingWritesTheFileAndReturnsAnOpaqueName() throws IOException {
        String name = adapter.store(USER, IMAGE);

        assertThat(name).matches("^[0-9a-f]{32}\\.jpg$");
        assertThat(directory.resolve(name)).exists();
        assertThat(Files.readAllBytes(directory.resolve(name))).isEqualTo(IMAGE);
    }

    @Test
    void thenameCarriesNothingAboutTheUserWhoUploadedIt() {
        String name = adapter.store(USER, IMAGE);

        // The name is handed out to the partner and sits in a URL a browser may log or cache.
        // A name derived from the user id would leak which account a photo belongs to, and a
        // predictable one would let somebody enumerate photos, which is the whole reason the
        // read endpoint can be public.
        assertThat(name).doesNotContain(USER.toString());
        assertThat(name).doesNotContain(USER.toString().replace("-", ""));
    }

    @Test
    void twouploadsNeverShareAname() {
        List<String> names =
                List.of(adapter.store(USER, IMAGE), adapter.store(USER, IMAGE), adapter.store(USER, IMAGE));

        // A stable name per user would be served from a stale cache after a change, which is
        // why the read response is allowed to cache for a year.
        assertThat(names).doesNotHaveDuplicates();
    }

    @Test
    void readingReturnsWhatWasStored() {
        String name = adapter.store(USER, IMAGE);

        assertThat(adapter.read(name)).contains(IMAGE);
    }

    @Test
    void readingAnameThatMatchesNothingIsEmptyRatherThanAnError() {
        assertThat(adapter.read("0123456789abcdef0123456789abcdef.jpg")).isEmpty();
    }

    @ParameterizedTest
    @ValueSource(
            strings = {
                "../../../../etc/passwd",
                "../secret.jpg",
                "..\\..\\windows\\system32\\config\\sam",
                "/etc/passwd",
                "C:\\Windows\\win.ini",
                "....//....//etc/passwd",
                "subdir/file.jpg",
                "name.jpg.exe",
                "ABCDEF0123456789abcdef0123456789.jpg",
                "0123456789abcdef0123456789abcdef.png",
                "0123456789abcdef0123456789abcde.jpg",
                ""
            })
    void anameThatIsNotOneWeGeneratedReadsAsNothing(String hostileName) {
        // Empty rather than an exception: the read endpoint is public, so a distinguishable
        // error would tell whoever is probing which names are the right shape.
        assertThat(adapter.read(hostileName)).isEmpty();
    }

    @ParameterizedTest
    @ValueSource(strings = {"../../etc/passwd", "/etc/passwd", "subdir/x.jpg", "name.jpg.exe"})
    void deletingAhostileNameTouchesNothing(String hostileName) throws IOException {
        Path bystander = directory.resolve("0123456789abcdef0123456789abcdef.jpg");
        Files.write(bystander, IMAGE);

        assertThatCode(() -> adapter.delete(hostileName)).doesNotThrowAnyException();

        assertThat(bystander).exists();
    }

    @Test
    void readingIsEmptyWhenTheNameIsNull() {
        assertThat(adapter.read(null)).isEmpty();
    }

    @Test
    void deletingRemovesTheFile() {
        String name = adapter.store(USER, IMAGE);

        adapter.delete(name);

        assertThat(directory.resolve(name)).doesNotExist();
        assertThat(adapter.read(name)).isEmpty();
    }

    @Test
    void deletingSomethingAlreadyGoneIsNotAnError() {
        String name = adapter.store(USER, IMAGE);
        adapter.delete(name);

        // Closing an account and replacing a photo can both reach this, and the outcome wanted
        // is "the file is not there", which is already true.
        assertThatCode(() -> adapter.delete(name)).doesNotThrowAnyException();
    }

    @Test
    void deletingNullIsNotAnError() {
        assertThatCode(() -> adapter.delete(null)).doesNotThrowAnyException();
    }

    @Test
    void storingLeavesNoTemporaryFileBehind() {
        adapter.store(USER, IMAGE);

        // The write goes to a temp file and is moved into place. A leftover .tmp would mean the
        // move failed silently, and they would pile up on the volume one per upload.
        assertThat(directory).isDirectoryNotContaining(path -> path.toString().endsWith(".tmp"));
    }

    @Test
    void thedirectoryIsCreatedWhenItDoesNotExistYet() {
        Path fresh = directory.resolve("not").resolve("there").resolve("yet");
        FilesystemAvatarStorageAdapter onFreshVolume = new FilesystemAvatarStorageAdapter(fresh.toString());

        onFreshVolume.prepareDirectory();

        // A new volume starts empty, and the first upload must not be the thing that discovers
        // the directory is missing.
        assertThat(fresh).isDirectory();
    }
}
